pipeline{
    agent any

    stages{

        stage('Checkout') {
            steps {
                git branch: 'main' , url: 'https://github.com/EVT98/terraform-vpc-ec2-alb.git'
            }
        }
        stage('init'){
            steps{
                sh 'terraform init -no-color'
            }
        }
        stage('validate'){
            steps{
                sh 'terraform validate -no-color'
            }
        }
          stage('format'){
            steps{
                sh 'terraform fmt -no-color'
            }
        }
          stage('plan'){
            steps{
                sh 'terraform plan -no-color'
            }
        }
    }
}
